 Que 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations

NumPy, short for Numerical Python, is primarily designed to facilitate numerical computations in Python. It provides:

Multi-dimensional Arrays: The core feature of NumPy is its ndarray (N-dimensional array), which allows for efficient storage and manipulation of large datasets.

Mathematical Functions: NumPy includes a comprehensive collection of mathematical functions that support operations on arrays, such as linear algebra, statistical analysis, and Fourier transforms.

Data Handling: It enables efficient data handling for tasks like data cleaning, transformation, and aggregation, making it suitable for preprocessing in machine learning and data analysis

Advantages of NumPy
Performance and Speed

  Speed Advantage: NumPy is significantly faster than traditional Python lists due to its implementation in C. Operations on NumPy arrays can be up to 50 times faster than those on lists because they are stored in contiguous memory locations, which enhances access speed1

  Vectorization: It supports vectorized operations, allowing users to perform element-wise operations on entire arrays without the need for explicit loops, thus improving performance2

Memory Efficiency

  Efficient Memory Usage: NumPy arrays require less memory than Python lists since they store elements of the same type. This uniformity reduces overhead and leads to more compact storage1

Rich Ecosystem Integration

  Compatibility with Other Libraries: NumPy seamlessly integrates with other scientific libraries such as SciPy (for advanced computations), Pandas (for data manipulation), Matplotlib (for visualization), and Scikit-learn (for machine learning). This interoperability enhances its functionality across various domains2


Broad Applications

  Scientific Computing: Used extensively in fields like physics, biology, finance, and engineering for simulations and modeling real-world systems1
  
  Machine Learning: Many machine learning frameworks rely on NumPy for handling numerical data efficiently. Its array operations form the backbone of algorithms used in AI and machine learning tasks2

Enhancements to Python's Capabilities
NumPy enhances Python's capabilities for numerical operations in several ways:

  High-Level Mathematical Functions: It provides high-level functions that simplify complex mathematical computations, making it easier for users to perform advanced analyses without needing extensive programming knowledge.

  Broadcasting Mechanism: This feature allows NumPy to perform arithmetic operations on arrays of different shapes without requiring explicit replication of data. This simplifies code and reduces memory usage1
    
  Universal Functions (ufuncs): These are functions that operate element-wise on arrays, enabling fast execution of mathematical operations across large datasets4
  
  Support for Multi-dimensional Data: Unlike traditional lists that are one-dimensional, NumPy can handle multi-dimensional data structures efficiently, which is crucial for many scientific applications.

In [ ]:
# Que 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other ?

# Feature	                          np.mean()	                                                                                np.average()
# Basic Functionality	              Computes the arithmetic mean of an array.	                                                Computes the weighted average of an array (if weights are provided).
# Weights Parameter	                Does not support weights.	                                                                Supports an optional weights parameter for calculating weighted averages.
# Handling of Masks	                Takes boolean masks into account, computing the mean only over unmasked data.	            Ignores boolean masks, computing the average over all data regardless of masking.


# When to Use Each Function

    # Use np.mean() when:
        # You need a simple arithmetic mean.
        # You want to take advantage of additional parameters like dtype for controlling the precision of calculations.
    # Use np.average() when:
        # You need to calculate a weighted average where different elements have different levels of importance.


In [1]:
# Que 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

# Reversing a NumPy array can be accomplished in various ways, depending on the dimensions of the array and the desired axis along which to reverse it.

# Methods for Reversing a NumPy Array
# 1. Using Slicing - Slicing is a straightforward method to reverse an array by specifying a step of -1.

import numpy as np

arr_1d = np.array([1,2,3,4,5])
reversed_arr_1d = arr_1d[::-1]
print("Reversed 1D Array: ", reversed_arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
reversed_arr_2d = np.flip(arr_2d)
print("Reversed 2D Array: ", reversed_arr_2d)

# other methods are - 2. Using np.flip() -  The np.flip() function reverses the order of elements along the specified axis or axes.
# 3. Using np.flipud() and np.fliplr() - These functions are specialized for flipping arrays up/down and left/right, respectively.



Reversed 1D Array:  [5 4 3 2 1]
Reversed 2D Array:  [[6 5 4]
 [3 2 1]]


In [ ]:
# Que 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

# To determine the data type of elements in a NumPy array, you can use the dtype attribute of the array. This attribute provides essential information about the type of data stored in the array, which is crucial for memory management and performance optimization in numerical computations.

# Determining Data Type
# Using the dtype Attribute
# The dtype attribute returns the data type of the elements in a NumPy array.

# Importance of Data Types

   # Memory Management:
        #Each data type in NumPy has a fixed size (in bytes), which allows NumPy to allocate memory efficiently. For instance, an int32 uses 4 bytes, while a float64 uses 8 bytes. By choosing the appropriate data type, you can minimize memory usage.

  # Performance Optimization:

    # Operations on arrays with specific data types can be faster because NumPy can leverage lower-level optimizations for those types. For example, operations on integers may be faster than on floating-point numbers due to less complexity in handling them.
    # Using appropriate data types can also prevent issues like overflow or underflow during calculations. For instance, using int8 for large numbers could lead to overflow errors.

  # Consistency:

    # All elements in a NumPy array must have the same data type. This consistency allows NumPy to perform element-wise operations efficiently and predictably.

  # Function Compatibility:

    # Some functions and operations are only compatible with specific data types. Knowing the data type helps avoid runtime errors and ensures that functions behave as expected.


In [ ]:
# Que 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# The ndarray (N-dimensional array) is the core data structure in NumPy, designed for efficient storage and manipulation of numerical data. Here’s a detailed overview of its key features and how it differs from standard Python lists.
# Definition and Key Features of ndarrays
# Definition
# An ndarray is a multidimensional, homogeneous array that holds items of the same data type. It is a fixed-size container that allows for efficient computation and manipulation of large datasets.
# Key Features

    # Homogeneity: All elements in an ndarray must be of the same type, which allows for optimized memory usage and performance. The data type can be specified using the dtype attribute.
    # N-Dimensional: Ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), making them suitable for representing complex data structures like matrices and tensors.
    # Contiguous Memory Layout: Elements are stored in contiguous blocks of memory, which enhances performance during computations due to better cache utilization.
    # Vectorized Operations: NumPy supports vectorized operations, allowing users to perform arithmetic operations on entire arrays without explicit loops. This leads to cleaner code and faster execution.
    # Broadcasting: Ndarrays can automatically expand their dimensions to perform operations on arrays of different shapes, enabling flexible arithmetic operations.
    # Rich Functionality: NumPy provides a wide range of mathematical functions and tools for linear algebra, statistics, and Fourier transforms that operate directly on ndarrays.
    # Indexing and Slicing: Ndarrays support advanced indexing and slicing techniques, allowing for easy access and manipulation of subarrays

# Feature	                          ndarrays	                                  Standard Python Lists
# Data Type	            Homogeneous (same type for all elements)	              Heterogeneous (different types allowed)
# Memory Efficiency	    More memory-efficient due to fixed size	                Less memory-efficient; overhead for each element
# Performance	          Faster operations due to contiguous memory	            Slower for numerical computations
# Operations	          Supports vectorized operations	                        Requires explicit loops for element-wise operations
# Dimensions	          Can be multi-dimensional (n-D)	                        Primarily one-dimensional; nested lists for multi-dimensional
# Functionality	        Extensive mathematical functions available	            Limited built-in fu



In [ ]:
# Que 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# Performance Benefits of NumPy Arrays
# 1. Speed of Operations
''' NumPy arrays are optimized for performance, especially in numerical computations. They are implemented in C and designed to operate on contiguous blocks of memory, which allows for faster execution of operations compared to Python lists.
    Creation Speed: Creating a NumPy array is significantly faster than creating a Python list. For instance, benchmarks show that NumPy can be approximately 25 times faster than lists for creating arrays with one million elements1
    Arithmetic Operations: NumPy excels in performing element-wise arithmetic operations. Operations like squaring elements can be up to 200 times faster with NumPy due to its vectorized operations, which eliminate the need for explicit loops1
    Mathematical Functions: Built-in mathematical functions (e.g., trigonometric calculations) are also optimized in NumPy. For example, computing the sine of elements in an array can be over 13 times faster with NumPy compared to using Python lists1

2. Memory Efficiency
NumPy arrays are more memory-efficient than Python lists because they store elements of the same type in a contiguous block of memory. This homogeneous storage reduces overhead and allows NumPy to use less memory overall.

    Reduced Memory Overhead: While a Python list can contain mixed types (integers, floats, strings), which incurs additional overhead, a NumPy array requires all elements to be of the same type, allowing for tighter packing and less wasted space5

3. Vectorization and Broadcasting
NumPy's ability to perform vectorized operations means that it can apply operations across entire arrays without the need for explicit loops. This not only simplifies code but also enhances performance.

    Broadcasting: This feature allows NumPy to perform arithmetic operations on arrays of different shapes by automatically expanding dimensions as needed. This capability leads to concise and efficient code that runs much faster than equivalent Python list operations1
    .

4. Optimized Aggregation Functions
Aggregating data (e.g., summing values) is significantly faster with NumPy. Benchmarks indicate that summing elements in a NumPy array can be over 22 times faster than summing values in a Python list1
. This is due to optimized implementations in NumPy that leverage its underlying data structures
'''

In [2]:
# Que 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# Feature	                              np.vstack()	                                                        np.hstack()
# Functionality	            Stacks arrays in sequence vertically (row-wise).	                    Stacks arrays in sequence horizontally (column-wise).
# Input Requirements	      Arrays must have the same shape along all but the first axis.        	Arrays must have the same shape along all but the second axis (1-D arrays can be of any length).
# Dimensionality	          Returns at least a 2-D array.                                        	Returns at least a 2-D array.


# Example of np.vstack()

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2))
print("Stacked Array (np.vstack()):\n", stacked_arr)

# Example of np.hstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.hstack((arr1, arr2))
print("Stacked Array (np.hstack()):\n", stacked_arr)


Stacked Array (np.vstack()):
 [[1 2 3]
 [4 5 6]]
Stacked Array (np.hstack()):
 [1 2 3 4 5 6]


In [4]:
# Que 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

# The np.fliplr() and np.flipud() functions in NumPy are designed to reverse the order of elements in arrays, but they do so along different axes. Here’s a detailed explanation of their differences, usage, and effects on various array dimensions.
# Differences Between fliplr() and flipud()
# Functionality

#    np.fliplr(m): Flips the input array left to right (i.e., reverses the order of columns). This means that for each row in a 2D array, the first column becomes the last, the second becomes the second last, and so on.
#    np.flipud(m): Flips the input array up to down (i.e., reverses the order of rows). For each column in a 2D array, the first row becomes the last, the second becomes the second last, etc.

# Input Requirements

#    Both functions require at least a 2D array as input. However, np.flipud() can also operate on 1D arrays, treating them as single-column arrays.

# Equivalent Operations

#    np.fliplr(m) is equivalent to slicing with m[:, ::-1], which reverses the columns.
#    np.flipud(m) is equivalent to slicing with m[::-1, ...], which reverses the rows.

# Effects on Various Array Dimensions

#For a 1D Array
array_1d = np.array([1, 2, 3])

flipped_ud_1d = np.flipud(array_1d)
print("Flipped Up to Down (1D):", flipped_ud_1d)


Flipped Up to Down (1D): [3 2 1]


In [6]:
# Que 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# The numpy.array_split() function is a versatile method in NumPy used to split an array into multiple sub-arrays. It is particularly useful for handling large datasets by breaking them down into smaller, more manageable pieces.

# Synax - numpy.array_split(ary, indices_or_sections, axis=0)

#Example  Uneven Splits

import numpy as np

# Create a 1D array
arr = np.arange(9)
# Split into 3 parts
result_uneven = np.array_split(arr, 3)
print("Split into 3 parts:", result_uneven)


Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
# Que 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations

# Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency of array operations. They allow for optimized computations by leveraging low-level implementations and eliminating the need for explicit loops in Python code. Here's a detailed exploration of both concepts.
# Vectorization
# Definition - Vectorization refers to the process of applying operations to entire arrays rather than individual elements. In NumPy, this is achieved through the use of built-in functions and operators that are optimized and implemented in low-level languages like C. This allows for operations to be executed simultaneously on multiple values, leading to significant performance improvements

# Broadcasting
# Definition - Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array across the larger one so that they have compatible dimensions for element-wise operations.

# Contribution to Efficient Array Operations
# Performance Enhancements

   # Speed: Both vectorization and broadcasting leverage optimized C code under the hood, significantly speeding up computations compared to traditional Python loops.
   # Memory Efficiency: Broadcasting minimizes memory usage by avoiding the need to create large temporary arrays when performing operations between differently shaped arrays.
   # Cleaner Code: These techniques lead to more concise and readable code by eliminating explicit loops and manual reshaping.



                                                  **PRACTICAL QUESTIONS**

In [1]:
# Que 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.\

import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

transposed_array = np.transpose(array)
print("Transposed Array:")
print(transposed_array)


Original Array:
[[50 81 27]
 [35 20 59]
 [28 73 45]]
Transposed Array:
[[50 35 28]
 [81 20 73]
 [27 59 45]]


In [4]:
# Que 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Create a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("Original 1D Array:")

print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("Reshaped into a 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("Reshaped into a 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]
Reshaped into a 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped into a 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
# Que 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.rand(4, 4)
print("Original Array:")
print(array)

# Add a border of zeros around the array
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Array with Border of Zeros:")
print(bordered_array)




Original Array:
[[0.06865417 0.42093393 0.90464416 0.292842  ]
 [0.93543246 0.21836083 0.91230705 0.84534129]
 [0.50347607 0.66661636 0.32661714 0.17161765]
 [0.09483905 0.36328496 0.44314528 0.91140464]]
Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06865417 0.42093393 0.90464416 0.292842   0.        ]
 [0.         0.93543246 0.21836083 0.91230705 0.84534129 0.        ]
 [0.         0.50347607 0.66661636 0.32661714 0.17161765 0.        ]
 [0.         0.09483905 0.36328496 0.44314528 0.91140464 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
# Que 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print(array)



[10 15 20 25 30 35 40 45 50 55 60]


In [8]:
# Que 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
strings_array = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")

print(strings_array)

# Apply different case transformations
uppercase_array = np.char.upper(strings_array)
lowercase_array = np.char.lower(strings_array)
titlecase_array = np.char.title(strings_array)

print("Uppercase Array:")
print(uppercase_array)

print("Lowercase Array:")
print(lowercase_array)

print("Titlecase Array:")
print(titlecase_array)



Original Array:
['python' 'numpy' 'pandas']
Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array:
['python' 'numpy' 'pandas']
Titlecase Array:
['Python' 'Numpy' 'Pandas']


In [10]:
# Que 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")

print(words_array)

# Insert a space between each character of every word
spaced_words_array = np

np.char.join(' ', words_array)
print("Spaced Array:")
print(spaced_words_array)

Original Array:
['python' 'numpy' 'pandas']
Spaced Array:
<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>


In [11]:
# Que 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = array1 + array2
print("Addition Result:")
print(addition_result)

# Element-wise subtraction
subtraction_result = array1 - array2
print("Subtraction Result:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = array1 * array2
print("Multiplication Result:")
print(multiplication_result)

# Element-wise division
division_result = array1 / array2
print("Division Result:")
print(division_result)

Addition Result:
[[ 6  8]
 [10 12]]
Subtraction Result:
[[-4 -4]
 [-4 -4]]
Multiplication Result:
[[ 5 12]
 [21 32]]
Division Result:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
# Que 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


In [17]:
# Que 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Function to check for prime numbers
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Display the prime numbers
print("Prime Numbers in the Array:")
print(prime_numbers)


Prime Numbers in the Array:
[733, 613, 173, 397, 563, 593, 293, 61, 983, 647, 283, 853, 479, 241, 281, 61, 127, 277, 911]


In [23]:
# Que 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(0, 101, size=30)  # Random temperatures between 0 and 100

# Print the daily temperatures
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into weeks (4 weeks of 7 days each, plus 2 extra days)
weekly_temperatures = daily_temperatures.reshape(-1, 7)

# Calculate weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)

# Display the weekly averages
print("\nWeekly Averages:")
for week_num, avg_temp in enumerate(weekly_averages, start=1):
    print(f"Week {week_num}: Average Temperature = {avg_temp:.2f} °C")
